config/routes.rb
Timetracker::Application.routes.draw do

  root 'companies#index'

  get 'recentworks/:days' => 'works#index'

  get 'timetrackerproject/:slug' => 'projects#show'

  resources :companies
  resources :projects
  resources :works

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :users
  has_many :projects

  validates :name, presence: true, length: { minimum: 5 }
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :company
  has_many :works
  has_many :users, through: :works

  validates :name, presence: true, length: { minimum: 5 }
  validates :default_rate, presence: true,
                           numericality: { only_integer: true,
                                           greater_than_or_equal_to: 50 }
  validates :company, presence: true
  validates :slug, length: { minimum: 3 }
  validates :slug, uniqueness: true


  scope :lowrate, -> { where("default_rate < 100") }
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :company
  has_many :works
  has_many :projects, through: :works

  validates :fname, presence: true,
                    length: { minimum: 2 }
  validates :lname, presence: true,
                    length: { minimum: 5 }
  validates :company, presence: true
end

app/models/work.rb
class Work < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  validates :hours, numericality: { only_integer: true, greater_than: 0,
                                    less_than_or_equal_to: 8 }
  validates :project, presence: true
  validates :user, presence: true
  validates :datetimeperformed, presence: true
  validate  :date_performed_cannot_be_in_the_future

  scope :fullday,-> { where("hours >= 8") }
  #scope :recent, -> { where("datetimeperformed > '#{Time.now - 7.days}'") }

  def self.recentdays(numdaysago)
    since_date = Time.now - numdaysago.to_i.days
    where("datetimeperformed > '#{since_date}'")
  end


  def date_performed_cannot_be_in_the_future
    if datetimeperformed.present? && datetimeperformed > Date.today
      errors.add(:datetimeperformed, "can't be in the future")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def show
    if (params[:slug])
      @project = Project.find_by slug: params[:slug]
    else
      @project = Project.find(params[:id])
    end
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController

  def index
    if (params[:days])
      @works = Work.recentdays(params[:days]).order('datetimeperformed desc')
    else
      @works = Work.all.order('datetimeperformed desc')
    end
  end

  def show
    @work = Work.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/companies/index.html.erb
<h1>Companies: index page</h1>
<p>
  Comapny listing
</p>

<ul>
  <% @companies.each do |company| %>
    <li><%= link_to company.name, company %></li>
  <% end %>
</ul>

app/views/companies/show.html.erb
<h1>Companies: show</h1>
<%= @company.name %>

<p>
  <%= link_to "All Companies", companies_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracker</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
  <header>
    Nav goes here
  </header>
  <section id="main">
    <article>
      <%= yield %>
    </article>
    <aside>
      <%= yield :aside %>
    </aside>
  </section>
  <footer>
    <p>
      Time Tracker is a <em>Sample Company</em> app.
    </p>
  </footer>
</div>
</body>
</html>

app/views/projects/index.html.erb
<h1>Projects listings:</h1>

<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<p>
  Company: <%= @project.company.name %>
</p>
<h3>Rate: <%= @project.default_rate %></h3>
<p>
  Slug: <%= @project.slug %>
</p>
<p>
  <%= link_to "All Projects", projects_path %>
</p>

app/views/works/index.html.erb
<h1>Work listings:</h1>

<ul>
  <% @works.each do |work| %>
    <li><%= link_to work.datetimeperformed, work %></li>
  <% end %>
</ul>

app/views/works/show.html.erb
<h1><%= @work.datetimeperformed %></h1>
<p>
  User: <%= @work.user.fname %> <%= @work.user.lname %>
</p>
<p>
  Project: <%= @work.project.name %>
</p>
<h3>Hours: <%= @work.hours %></h3>
<p>
  <%= link_to "All Works", works_path %>
</p>